CREATE TABLE ADMINISTRADOR( 
	Email VARCHAR(45),
	Nome VARCHAR(45) NOT NULL,
	Login VARCHAR(15) NOT NULL UNIQUE,
	Senha VARCHAR(32) NOT NULL,
	Cidade VARCHAR(45) NOT NULL,
	Rua VARCHAR(60) NOT NULL,
	Numero VARCHAR(8) NOT NULL,
	PRIMARY KEY(Email)
);

CREATE TABLE ALUNO(
	Matricula VARCHAR(45),
	Email VARCHAR(45) NOT NULL UNIQUE,
	Nome VARCHAR(45) NOT NULL,
	Login VARCHAR(15) NOT NULL UNIQUE,
	Senha VARCHAR(32) NOT NULL,
	Cidade VARCHAR(45) NOT NULL,
	Rua VARCHAR(60) NOT NULL,
	Numero VARCHAR(8) NOT NULL,
	NomeCurso VARCHAR(45) NOT NULL,
	PRIMARY KEY(Matricula)
);

CREATE TABLE ENQUETE(
	Id SERIAL,
	Nome VARCHAR(50) NOT NULL UNIQUE,
	Descricao VARCHAR(500),
	Foto VARCHAR,
	emailAdmin VARCHAR(45) NOT NULL,
	FOREIGN KEY(emailAdmin) REFERENCES Administrador(email) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY(Id)
);

CREATE TABLE COMENTARIOS(
	Id SERIAL,
	idEnquete INTEGER NOT NULL,
	Comentario VARCHAR(500) NOT NULL,
	FOREIGN KEY(idEnquete) REFERENCES Enquete(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY(Id)
);

CREATE TABLE OPCOES(
	Id SERIAL,
	idEnquete INTEGER NOT NULL, 
	Opcao VARCHAR NOT NULL,
	FOREIGN KEY(idEnquete) REFERENCES Enquete(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY(Id),
	UNIQUE(idEnquete, Opcao)
);

CREATE TABLE CURSO(
	Nome VARCHAR(45),
	Descricao VARCHAR NOT NULL,
	PRIMARY KEY(Nome)
);

CREATE TABLE SETOR(
	Nome VARCHAR(45),
	PRIMARY KEY(Nome)
);

ALTER TABLE Aluno ADD CONSTRAINT FKAlunoCurso FOREIGN KEY(NomeCurso) REFERENCES Curso(Nome) ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE RESPONDEENQUETE(
	matriculaAluno VARCHAR(45),
	idEnquete INTEGER,
	Resposta VARCHAR,
	FOREIGN KEY(matriculaAluno) REFERENCES Aluno(Matricula) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(idEnquete) REFERENCES Enquete(Id) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY(matriculaAluno, idEnquete)
);

CREATE TABLE ENQUETESCURSO(
	idEnquete INTEGER,
	nomeCurso VARCHAR(45),
	FOREIGN KEY(idEnquete) REFERENCES Enquete(Id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(nomeCurso) REFERENCES Curso(Nome) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY(idEnquete, nomeCurso)
);

CREATE TABLE ENQUETESSETOR(
	idEnquete INTEGER,
	nomeSetor VARCHAR(45),
	FOREIGN KEY(idEnquete) REFERENCES Enquete(Id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(nomeSetor) REFERENCES Setor(Nome) ON DELETE RESTRICT ON UPDATE CASCADE,
	PRIMARY KEY(idEnquete, nomeSetor)
);